# This is the network config written by 'subiquity'
network:
  ethernets:
    eth0:
      dhcp4: no
      addresses:
          - 10.30.110.208/29
      gateway4: 10.52.22.1
      nameservers:
          addresses: [10.51.1.10, 10.52.22.5]
    eth1:
      dhcp4: yes
  version: 2
