# This is the network config written by 'subiquity'
network:
  ethernets:
    eth0:
      dhcp4: no
      addresses:
          - <IP>/29
      gateway4: 10.30.22.7
      nameservers:
          addresses: [10.51.1.10, 10.52.22.5]
    eth1:
      dhcp4: yes
  version: 2
