# This is the network config written by 'subiquity'
network:
  ethernets:
    eth0:
      dhcp4: yes
      dhcp4-overrides:
         use-dns: no
      addresses:
         - <IP>/21
      nameservers:
         addresses: [10.52.22.1,10.51.1.10,10.52.2.5]
    eth1:
      dhcp4: yes
  version: 2